#!/usr/bin/python

from mininet.net import Mininet
from mininet.cli import CLI
from mininet.log import setLogLevel, info
from mininet.link import TCLink

from conf import s1 as sw1
from conf import s2 as sw2
from conf import s3 as sw3
from conf import s4 as sw4

def ovsns():

    "Create an empty network and add nodes to it."

    net = Mininet( topo=None,
                   build=False,
                   autoSetMacs=True,
                   link=TCLink
                 )

    s1 = net.addHost( sw1.nome, ip=sw1.ip )   
    s2 = net.addHost( sw2.nome, ip=sw2.ip )
    s3 = net.addHost( sw3.nome, ip=sw3.ip )
    s4 = net.addHost( sw4.nome, ip=sw4.ip )

    '''s1 = net.addHost( 's1', ip='0.0.0.0' ) 
    s2 = net.addHost( 's2', ip='0.0.0.0' )
    s3 = net.addHost( 's3', ip='0.0.0.0' ) 
    s4 = net.addHost( 's4', ip='0.0.0.0' ) '''

    h1 = net.addHost( 'h1', ip='10.0.0.1/8' )
    h2 = net.addHost( 'h2', ip='20.0.0.1/8' )
    h3 = net.addHost( 'h3', ip='30.0.0.1/8' )
    h4 = net.addHost( 'h4', ip='40.0.0.1/8' )
    h5 = net.addHost( 'h5', ip='10.0.0.5/8' )
    h6 = net.addHost( 'h6', ip='10.0.0.6/8' )
    h7 = net.addHost( 'h7', ip='10.0.0.7/8' )
    h8 = net.addHost( 'h8', ip='10.0.0.8/8' )
    h9 = net.addHost( 'h9', ip='10.0.0.9/8' )
    h10 = net.addHost( 'h10', ip='10.0.0.100/8' )
    h11 = net.addHost( 'h11', ip='10.0.0.11/8' )
    h12 = net.addHost( 'h12', ip='10.0.0.12/8' )    
    h13 = net.addHost( 'h13', ip='10.0.0.13/8' )
    h14 = net.addHost( 'h14', ip='10.0.0.14/8' )
    h15 = net.addHost( 'h15', ip='10.0.0.15/8' )
    h16 = net.addHost( 'h16', ip='10.0.0.16/8' )
    h17 = net.addHost( 'h17', ip='10.0.0.17/8' )
    h18 = net.addHost( 'h18', ip='10.0.0.18/8' )
    h19 = net.addHost( 'h19', ip='10.0.0.19/8' )
    h20 = net.addHost( 'h20', ip='10.0.0.20/8' )
    h21 = net.addHost( 'h21', ip='10.0.0.21/8' )
    h22 = net.addHost( 'h22', ip='10.0.0.22/8' )
    h23 = net.addHost( 'h23', ip='10.0.0.23/8' )
    h24 = net.addHost( 'h24', ip='10.0.0.24/8' )
    h25 = net.addHost( 'h25', ip='10.0.0.25/8' )
    h26 = net.addHost( 'h26', ip='10.0.0.26/8' )
    h27 = net.addHost( 'h27', ip='10.0.0.27/8' )
    h28 = net.addHost( 'h28', ip='10.0.0.28/8' )
    h29 = net.addHost( 'h29', ip='10.0.0.29/8' )
    h30 = net.addHost( 'h30', ip='10.0.0.30/8' )
    h31 = net.addHost( 'h31', ip='10.0.0.31/8' ) 
    h32 = net.addHost( 'h32', ip='10.0.0.32/8' )
    h33 = net.addHost( 'h33', ip='10.0.0.33/8' )
    h34 = net.addHost( 'h34', ip='10.0.0.34/8' )
    h35 = net.addHost( 'h35', ip='10.0.0.35/8' )
    h36 = net.addHost( 'h36', ip='10.0.0.36/8' )
    h37 = net.addHost( 'h37', ip='10.0.0.37/8' )
    h38 = net.addHost( 'h38', ip='10.0.0.38/8' )
    h39 = net.addHost( 'h39', ip='10.0.0.39/8' )
    h40 = net.addHost( 'h40', ip='10.0.0.40/8' )
    h41 = net.addHost( 'h41', ip='10.0.0.41/8' ) 
    h42 = net.addHost( 'h42', ip='10.0.0.42/8' )
    h43 = net.addHost( 'h43', ip='10.0.0.43/8' )
    h44 = net.addHost( 'h44', ip='10.0.0.44/8' )
    h45 = net.addHost( 'h45', ip='10.0.0.45/8' )
    h46 = net.addHost( 'h46', ip='10.0.0.46/8' )
    h47 = net.addHost( 'h47', ip='10.0.0.47/8' )
    h48 = net.addHost( 'h48', ip='10.0.0.48/8' )
    h49 = net.addHost( 'h49', ip='10.0.0.49/8' )
    h50 = net.addHost( 'h50', ip='10.0.0.50/8' )
        
    
       
    net.addLink( h1, s1, bw=100 )    
    net.addLink( s1, s2, bw=100 )
    net.addLink( s2, s3, bw=100 )
    net.addLink( s2, h2, bw=100 )
    net.addLink( s3, h3, bw=100 )
    net.addLink( s3, s1, bw=100 )
    net.addLink( h5, s1, bw=100 )
    net.addLink( s3, s4, bw=100 )
    net.addLink( s4, h4, bw=100 )
    net.addLink( s4, s1, bw=100 )
    net.addLink( h6, s1, bw=100 )
    net.addLink( h7, s1, bw=100 )
    net.addLink( h8, s1, bw=100 )
    net.addLink( h9, s1, bw=100 )
    net.addLink( h10, s1, bw=100 )
    net.addLink( h11, s1, bw=100 )
    net.addLink( h12, s1, bw=100 )
    net.addLink( h13, s1, bw=100 )
    net.addLink( h14, s1, bw=100 )
    net.addLink( h15, s1, bw=100 )
    net.addLink( h16, s1, bw=100 )
    net.addLink( h17, s1, bw=100 )
    net.addLink( h18, s1, bw=100 )
    net.addLink( h19, s1, bw=100 )
    net.addLink( h20, s1, bw=100 )
    net.addLink( h21, s1, bw=100 )
    net.addLink( h22, s1, bw=100 )
    net.addLink( h23, s1, bw=100 )
    net.addLink( h24, s1, bw=100 )
    net.addLink( h25, s1, bw=100 )
    net.addLink( h26, s1, bw=100 )
    net.addLink( h27, s1, bw=100 )
    net.addLink( h28, s1, bw=100 )
    net.addLink( h29, s1, bw=100 )
    net.addLink( h30, s1, bw=100 )
    net.addLink( h31, s1, bw=100 )
    net.addLink( h32, s1, bw=100 )
    net.addLink( h33, s1, bw=100 )
    net.addLink( h34, s1, bw=100 )
    net.addLink( h35, s1, bw=100 )
    net.addLink( h36, s1, bw=100 )
    net.addLink( h37, s1, bw=100 )
    net.addLink( h38, s1, bw=100 )
    net.addLink( h39, s1, bw=100 )
    net.addLink( h40, s1, bw=100 )
    net.addLink( h41, s1, bw=100 )
    net.addLink( h42, s1, bw=100 )
    net.addLink( h43, s1, bw=100 )
    net.addLink( h44, s1, bw=100 )
    net.addLink( h45, s1, bw=100 )
    net.addLink( h46, s1, bw=100 )
    net.addLink( h47, s1, bw=100 )
    net.addLink( h48, s1, bw=100 )
    net.addLink( h49, s1, bw=100 )
    net.addLink( h50, s1, bw=100 )

    net.start()
    CLI( net )
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    ovsns()    
